// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'localhost:8080/api/v1' | (string & {});
};

export type ServerResponseError = {
    error?: string;
    request_id?: string;
};

export type TenantRequestId = {
    id: string;
};

export type TenantRequestMember = {
    /**
     * TODO Как валидировать ?
     */
    admin?: boolean;
    id: string;
};

export type TenantRequestName = {
    name: string;
};

export type TenantResponseMember = {
    admin?: boolean;
    id?: string;
    name?: string;
    since?: number;
};

export type TenantResponseMembersList = {
    members?: Array<TenantResponseMember>;
};

export type TenantResponseSingleMember = {
    member?: TenantResponseMember;
};

export type TenantResponseSingleTenant = {
    tenant?: TenantResponseTenant;
};

export type TenantResponseTenant = {
    admin?: boolean;
    id?: string;
    name?: string;
    since?: number;
};

export type TenantResponseTenantsList = {
    tenants?: Array<TenantResponseTenant>;
};

export type UserRequestCode = {
    code: string;
};

export type UserRequestContact = {
    kind: 'email' | 'telegram';
    value: string;
};

export type UserRequestEmail = {
    email: string;
};

export type UserRequestEmailCode = {
    code: string;
    email: string;
};

export type UserRequestParameter = {
    kind: 'first_name' | 'last_name' | 'timezone' | 'language';
    value: string;
};

export type UserResponseAccessJwt = {
    token?: string;
    type?: string;
};

export type UserResponseContact = {
    id?: string;
    kind?: string;
    value?: string;
    verified?: boolean;
};

export type UserResponseContactsList = {
    contacts?: Array<UserResponseContact>;
};

export type UserResponseSession = {
    current?: boolean;
    device?: string;
    id?: string;
    since?: number;
};

export type UserResponseSessions = {
    sessions?: Array<UserResponseSession>;
};

export type UserResponseSingleContact = {
    contact?: UserResponseContact;
};

export type UserResponseUser = {
    first_name?: string;
    id?: string;
    last_name?: string;
    timezone?: string;
};

export type GetAuthLoginByProviderData = {
    body?: never;
    path: {
        /**
         * OAuth provider: yandex, vk, keycloak
         */
        provider: string;
    };
    query?: never;
    url: '/auth/login/{provider}';
};

export type GetAuthLoginByProviderCallbackData = {
    body?: never;
    path: {
        /**
         * OAuth provider: yandex, vk, keycloak
         */
        provider: string;
    };
    query?: never;
    url: '/auth/login/{provider}/callback';
};

export type PostAuthLoginEmailData = {
    /**
     * Request JSON
     */
    body: UserRequestEmailCode;
    path?: never;
    query?: never;
    url: '/auth/login/email';
};

export type PostAuthLoginEmailErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAuthLoginEmailError = PostAuthLoginEmailErrors[keyof PostAuthLoginEmailErrors];

export type PostAuthLoginEmailResponses = {
    /**
     * OK
     */
    200: UserResponseAccessJwt;
};

export type PostAuthLoginEmailResponse = PostAuthLoginEmailResponses[keyof PostAuthLoginEmailResponses];

export type PostAuthLoginEmailCodeData = {
    /**
     * Request JSON
     */
    body: UserRequestEmail;
    path?: never;
    query?: never;
    url: '/auth/login/email/code';
};

export type PostAuthLoginEmailCodeErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAuthLoginEmailCodeError = PostAuthLoginEmailCodeErrors[keyof PostAuthLoginEmailCodeErrors];

export type PostAuthLoginEmailCodeResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostAuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * OK
     */
    200: UserResponseAccessJwt;
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type GetTenantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants';
};

export type GetTenantsErrors = {
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetTenantsError = GetTenantsErrors[keyof GetTenantsErrors];

export type GetTenantsResponses = {
    /**
     * OK
     */
    200: TenantResponseTenantsList;
};

export type GetTenantsResponse = GetTenantsResponses[keyof GetTenantsResponses];

export type GetTenantsByIdMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants/{id}/members';
};

export type GetTenantsByIdMembersErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetTenantsByIdMembersError = GetTenantsByIdMembersErrors[keyof GetTenantsByIdMembersErrors];

export type GetTenantsByIdMembersResponses = {
    /**
     * OK
     */
    200: TenantResponseMembersList;
};

export type GetTenantsByIdMembersResponse = GetTenantsByIdMembersResponses[keyof GetTenantsByIdMembersResponses];

export type PostTenantsByIdMembersDeleteData = {
    /**
     * Request JSON
     */
    body: TenantRequestId;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/members/delete';
};

export type PostTenantsByIdMembersDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsByIdMembersDeleteError = PostTenantsByIdMembersDeleteErrors[keyof PostTenantsByIdMembersDeleteErrors];

export type PostTenantsByIdMembersDeleteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostTenantsByIdMembersUpdateData = {
    /**
     * Request JSON
     */
    body: TenantRequestMember;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/members/update';
};

export type PostTenantsByIdMembersUpdateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsByIdMembersUpdateError = PostTenantsByIdMembersUpdateErrors[keyof PostTenantsByIdMembersUpdateErrors];

export type PostTenantsByIdMembersUpdateResponses = {
    /**
     * OK
     */
    200: TenantResponseSingleMember;
};

export type PostTenantsByIdMembersUpdateResponse = PostTenantsByIdMembersUpdateResponses[keyof PostTenantsByIdMembersUpdateResponses];

export type GetTenantsByIdTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants/{id}/tokens';
};

export type GetTenantsByIdTokensErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetTenantsByIdTokensError = GetTenantsByIdTokensErrors[keyof GetTenantsByIdTokensErrors];

export type GetTenantsByIdTokensResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetTenantsByIdTokensResponse = GetTenantsByIdTokensResponses[keyof GetTenantsByIdTokensResponses];

export type PostTenantsByIdTokensCreateData = {
    /**
     * Request JSON
     */
    body: TenantRequestName;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/tokens/create';
};

export type PostTenantsByIdTokensCreateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsByIdTokensCreateError = PostTenantsByIdTokensCreateErrors[keyof PostTenantsByIdTokensCreateErrors];

export type PostTenantsByIdTokensCreateResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostTenantsByIdTokensCreateResponse = PostTenantsByIdTokensCreateResponses[keyof PostTenantsByIdTokensCreateResponses];

export type PostTenantsByIdTokensDeleteData = {
    /**
     * Request JSON
     */
    body: TenantRequestId;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/tokens/delete';
};

export type PostTenantsByIdTokensDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
};

export type PostTenantsByIdTokensDeleteError = PostTenantsByIdTokensDeleteErrors[keyof PostTenantsByIdTokensDeleteErrors];

export type PostTenantsByIdTokensDeleteResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostTenantsByIdTokensDeleteResponse = PostTenantsByIdTokensDeleteResponses[keyof PostTenantsByIdTokensDeleteResponses];

export type PostTenantsByIdUpdateData = {
    /**
     * Request JSON
     */
    body: TenantRequestName;
    path?: never;
    query?: never;
    url: '/tenants/{id}/update';
};

export type PostTenantsByIdUpdateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsByIdUpdateError = PostTenantsByIdUpdateErrors[keyof PostTenantsByIdUpdateErrors];

export type PostTenantsByIdUpdateResponses = {
    /**
     * Created
     */
    201: TenantResponseSingleTenant;
};

export type PostTenantsByIdUpdateResponse = PostTenantsByIdUpdateResponses[keyof PostTenantsByIdUpdateResponses];

export type PostTenantsCreateData = {
    /**
     * Request JSON
     */
    body: TenantRequestName;
    path?: never;
    query?: never;
    url: '/tenants/create';
};

export type PostTenantsCreateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsCreateError = PostTenantsCreateErrors[keyof PostTenantsCreateErrors];

export type PostTenantsCreateResponses = {
    /**
     * Created
     */
    201: TenantResponseSingleTenant;
};

export type PostTenantsCreateResponse = PostTenantsCreateResponses[keyof PostTenantsCreateResponses];

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type GetUserErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * OK
     */
    200: UserResponseUser;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetUserContactsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/contacts';
};

export type GetUserContactsErrors = {
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetUserContactsError = GetUserContactsErrors[keyof GetUserContactsErrors];

export type GetUserContactsResponses = {
    /**
     * OK
     */
    200: UserResponseContactsList;
};

export type GetUserContactsResponse = GetUserContactsResponses[keyof GetUserContactsResponses];

export type PostUserContactsByIdDeleteData = {
    body?: never;
    path: {
        /**
         * Contact ID
         */
        id: string;
    };
    query?: never;
    url: '/user/contacts/{id}/delete';
};

export type PostUserContactsByIdDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostUserContactsByIdDeleteError = PostUserContactsByIdDeleteErrors[keyof PostUserContactsByIdDeleteErrors];

export type PostUserContactsByIdDeleteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostUserContactsByIdVerifyData = {
    /**
     * Request JSON
     */
    body: UserRequestCode;
    path: {
        /**
         * Contact ID
         */
        id: string;
    };
    query?: never;
    url: '/user/contacts/{id}/verify';
};

export type PostUserContactsByIdVerifyErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostUserContactsByIdVerifyError = PostUserContactsByIdVerifyErrors[keyof PostUserContactsByIdVerifyErrors];

export type PostUserContactsByIdVerifyResponses = {
    /**
     * OK
     */
    200: UserResponseSingleContact;
};

export type PostUserContactsByIdVerifyResponse = PostUserContactsByIdVerifyResponses[keyof PostUserContactsByIdVerifyResponses];

export type PostUserContactsAddData = {
    /**
     * Request JSON
     */
    body: UserRequestContact;
    path?: never;
    query?: never;
    url: '/user/contacts/add';
};

export type PostUserContactsAddErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostUserContactsAddError = PostUserContactsAddErrors[keyof PostUserContactsAddErrors];

export type PostUserContactsAddResponses = {
    /**
     * Created
     */
    201: UserResponseSingleContact;
};

export type PostUserContactsAddResponse = PostUserContactsAddResponses[keyof PostUserContactsAddResponses];

export type GetUserSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/sessions';
};

export type GetUserSessionsErrors = {
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetUserSessionsError = GetUserSessionsErrors[keyof GetUserSessionsErrors];

export type GetUserSessionsResponses = {
    /**
     * OK
     */
    200: UserResponseSessions;
};

export type GetUserSessionsResponse = GetUserSessionsResponses[keyof GetUserSessionsResponses];

export type PostUserSessionsCloseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/sessions/close';
};

export type PostUserSessionsCloseErrors = {
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostUserSessionsCloseError = PostUserSessionsCloseErrors[keyof PostUserSessionsCloseErrors];

export type PostUserSessionsCloseResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostUserUpdateData = {
    /**
     * Request JSON
     */
    body: UserRequestParameter;
    path?: never;
    query?: never;
    url: '/user/update';
};

export type PostUserUpdateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostUserUpdateError = PostUserUpdateErrors[keyof PostUserUpdateErrors];

export type PostUserUpdateResponses = {
    /**
     * OK
     */
    200: UserResponseUser;
};

export type PostUserUpdateResponse = PostUserUpdateResponses[keyof PostUserUpdateResponses];
