// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'localhost:8080/api/v1' | (string & {});
};

export type EventRequestComment = {
    text: string;
};

export type EventRequestId = {
    id: string;
};

export type EventRequestIncident = {
    description?: string;
    tenant: EventRequestId;
    title: string;
};

export type EventRequestKey = {
    key: string;
};

export type EventRequestKeyValue = {
    key: string;
    value: string;
};

export type EventRequestStatus = {
    status: 'acknowledged' | 'resolved';
};

export type EventResponseAlert = {
    annotations: Array<EventResponseAnnotation>;
    comments: Array<EventResponseComment>;
    description?: string;
    id: string;
    labels: Array<EventResponseLabel>;
    occurrence_times: Array<number>;
    source: string;
    statuses: Array<EventResponseStatus>;
    tenant: EventResponseTenant;
    time: number;
};

export type EventResponseAlertList = {
    alerts: Array<EventResponseAlert>;
    total: number;
};

export type EventResponseAlertsStats = {
    acknowledged: EventResponseAlertsStatusStat;
    created: EventResponseAlertsStatusStat;
    resolved: EventResponseAlertsStatusStat;
};

export type EventResponseAlertsStatusStat = {
    timestamp: Array<number>;
    value: Array<number>;
};

export type EventResponseAnnotation = {
    created: number;
    creator?: string;
    deleted?: number;
    deleter?: string;
    key: string;
    value: string;
};

export type EventResponseComment = {
    created: number;
    creator: string;
    deleted?: number;
    deleter?: string;
    id: string;
    text: string;
};

export type EventResponseIncident = {
    alerts: Array<EventResponseAlert>;
    comments: Array<EventResponseComment>;
    description?: string;
    id: string;
    labels: Array<EventResponseLabel>;
    statuses: Array<EventResponseStatus>;
    tenant: EventResponseTenant;
    time: number;
    title: string;
};

export type EventResponseIncidentList = {
    incidents: Array<EventResponseIncident>;
    total: number;
};

export type EventResponseLabel = {
    created: number;
    creator?: string;
    deleted?: number;
    deleter?: string;
    key: string;
    value: string;
};

export type EventResponseSingleAlert = {
    alert: EventResponseAlert;
};

export type EventResponseSingleIncident = {
    incident: EventResponseIncident;
};

export type EventResponseStatus = {
    created: number;
    creator?: string;
    status: string;
};

export type EventResponseTenant = {
    id: string;
};

export type ServerResponseError = {
    error?: string;
    request_id?: string;
};

export type SettingsResponseAuthProvider = {
    name: string;
};

export type SettingsResponseAuthProviderList = {
    providers: Array<SettingsResponseAuthProvider>;
};

export type SettingsResponseFeature = {
    enabled: boolean;
    key: string;
    value?: string;
};

export type SettingsResponseFeatureList = {
    features: Array<SettingsResponseFeature>;
};

export type TenantRequestCondition = {
    event?: 'alert' | 'incident';
    labels?: {
        [key: string]: string;
    };
    name?: string;
};

export type TenantRequestEscalation = {
    enabled?: boolean;
    name: string;
};

export type TenantRequestId = {
    id: string;
};

export type TenantRequestMember = {
    id: string;
    role: 'watcher' | 'member' | 'admin';
};

export type TenantRequestName = {
    name: string;
};

export type TenantRequestNewSchedule = {
    name: string;
    since: number;
    until?: number;
};

export type TenantRequestNumber = {
    number: number;
};

export type TenantRequestOverride = {
    duration: number;
    member: string;
    name: string;
    rotation: number;
    since: number;
};

export type TenantRequestRotation = {
    days: Array<number>;
    duration: number;
    members: Array<string>;
    name: string;
    since: number;
};

export type TenantRequestSchedule = {
    name: string;
    until?: number;
};

export type TenantRequestStep = {
    delay?: number;
    member?: string;
    name?: string;
    schedule?: TenantRequestStepSchedule;
};

export type TenantRequestStepSchedule = {
    id: string;
    position: 'current' | 'next' | 'previous' | 'all';
};

export type TenantResponseCondition = {
    created: number;
    creator: string;
    event?: string;
    labels?: {
        [key: string]: string;
    };
    name?: string;
    number: number;
};

export type TenantResponseEscalation = {
    conditions: Array<TenantResponseCondition>;
    created: number;
    creator: string;
    enabled: boolean;
    id: string;
    name: string;
    steps: Array<TenantResponseStep>;
    updated?: number;
    updater?: string;
};

export type TenantResponseEscalationList = {
    escalations: Array<TenantResponseEscalation>;
};

export type TenantResponseMember = {
    id: string;
    role: string;
    since: number;
};

export type TenantResponseMemberList = {
    members: Array<TenantResponseMember>;
};

export type TenantResponseOverride = {
    created: number;
    creator: string;
    name: string;
    number: number;
    rotation: number;
    shift: TenantResponseShift;
};

export type TenantResponseRotation = {
    created: number;
    creator: string;
    members: Array<string>;
    name: string;
    number: number;
    shifts?: Array<TenantResponseShift>;
};

export type TenantResponseSchedule = {
    created: number;
    creator: string;
    id: string;
    name: string;
    overrides?: Array<TenantResponseOverride>;
    rotations?: Array<TenantResponseRotation>;
    since: number;
    tenant: TenantResponseTenant;
    until?: number;
    updated?: number;
    updater?: string;
};

export type TenantResponseScheduleList = {
    schedules: Array<TenantResponseSchedule>;
};

export type TenantResponseShift = {
    member: string;
    since: number;
    until: number;
};

export type TenantResponseShiftList = {
    shifts: Array<TenantResponseShift>;
};

export type TenantResponseSingleCondition = {
    condition: TenantResponseCondition;
};

export type TenantResponseSingleEscalation = {
    escalation: TenantResponseEscalation;
};

export type TenantResponseSingleMember = {
    member: TenantResponseMember;
};

export type TenantResponseSingleOverride = {
    rotation: TenantResponseOverride;
};

export type TenantResponseSingleRotation = {
    rotation: TenantResponseRotation;
};

export type TenantResponseSingleSchedule = {
    schedule: TenantResponseSchedule;
};

export type TenantResponseSingleStep = {
    step: TenantResponseStep;
};

export type TenantResponseSingleTenant = {
    tenant: TenantResponseTenant;
};

export type TenantResponseSingleToken = {
    token: TenantResponseToken;
};

export type TenantResponseStep = {
    created: number;
    creator: string;
    delay: number;
    member?: string;
    name?: string;
    number: number;
    schedule?: TenantResponseStepSchedule;
};

export type TenantResponseStepSchedule = {
    id: string;
    name: string;
    position?: 'current' | 'next' | 'previous' | 'all';
};

export type TenantResponseTenant = {
    id: string;
    name: string;
    role: string;
    since: number;
};

export type TenantResponseTenantList = {
    tenants: Array<TenantResponseTenant>;
};

export type TenantResponseToken = {
    created: number;
    creator: string;
    id: string;
    name: string;
    value?: string;
};

export type TenantResponseTokenList = {
    tokens: Array<TenantResponseToken>;
};

export type UserRequestCode = {
    code: string;
};

export type UserRequestContact = {
    kind: 'email' | 'telegram';
    value: string;
};

export type UserRequestEmail = {
    email: string;
};

export type UserRequestEmailCode = {
    code: string;
    email: string;
};

export type UserRequestParameter = {
    kind: 'first_name' | 'last_name' | 'timezone' | 'language';
    value: string;
};

export type UserResponseAccessJwt = {
    token: string;
    type: string;
};

export type UserResponseContact = {
    id: string;
    kind: 'email' | 'telegram';
    value: string;
    verified: boolean;
};

export type UserResponseContactsList = {
    contacts: Array<UserResponseContact>;
};

export type UserResponseSession = {
    current: boolean;
    device: string;
    id: string;
    since: number;
};

export type UserResponseSessions = {
    sessions: Array<UserResponseSession>;
};

export type UserResponseSingleContact = {
    contact: UserResponseContact;
};

export type UserResponseSingleUser = {
    user: UserResponseUser;
};

export type UserResponseUser = {
    first_name?: string;
    id: string;
    last_name?: string;
    timezone?: string;
};

export type GetAlertsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Alerts limit
         */
        limit?: number;
        /**
         * Alerts offset
         */
        offset?: number;
    };
    url: '/alerts';
};

export type GetAlertsErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetAlertsError = GetAlertsErrors[keyof GetAlertsErrors];

export type GetAlertsResponses = {
    /**
     * OK
     */
    200: EventResponseAlertList;
};

export type GetAlertsResponse = GetAlertsResponses[keyof GetAlertsResponses];

export type GetAlertsByIdData = {
    body?: never;
    path: {
        /**
         * Alert ID
         */
        id: string;
    };
    query?: never;
    url: '/alerts/{id}';
};

export type GetAlertsByIdErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetAlertsByIdError = GetAlertsByIdErrors[keyof GetAlertsByIdErrors];

export type GetAlertsByIdResponses = {
    /**
     * OK
     */
    200: EventResponseSingleAlert;
};

export type GetAlertsByIdResponse = GetAlertsByIdResponses[keyof GetAlertsByIdResponses];

export type PostAlertsByIdAnnotationsAddData = {
    /**
     * Request JSON
     */
    body: EventRequestKeyValue;
    path: {
        /**
         * Alert ID
         */
        id: string;
    };
    query?: never;
    url: '/alerts/{id}/annotations/add';
};

export type PostAlertsByIdAnnotationsAddErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAlertsByIdAnnotationsAddError = PostAlertsByIdAnnotationsAddErrors[keyof PostAlertsByIdAnnotationsAddErrors];

export type PostAlertsByIdAnnotationsAddResponses = {
    /**
     * OK
     */
    200: EventResponseSingleAlert;
};

export type PostAlertsByIdAnnotationsAddResponse = PostAlertsByIdAnnotationsAddResponses[keyof PostAlertsByIdAnnotationsAddResponses];

export type PostAlertsByIdAnnotationsDeleteData = {
    /**
     * Request JSON
     */
    body: EventRequestKey;
    path: {
        /**
         * Alert ID
         */
        id: string;
    };
    query?: never;
    url: '/alerts/{id}/annotations/delete';
};

export type PostAlertsByIdAnnotationsDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAlertsByIdAnnotationsDeleteError = PostAlertsByIdAnnotationsDeleteErrors[keyof PostAlertsByIdAnnotationsDeleteErrors];

export type PostAlertsByIdAnnotationsDeleteResponses = {
    /**
     * OK
     */
    200: EventResponseSingleAlert;
};

export type PostAlertsByIdAnnotationsDeleteResponse = PostAlertsByIdAnnotationsDeleteResponses[keyof PostAlertsByIdAnnotationsDeleteResponses];

export type PostAlertsByIdCommentsAddData = {
    /**
     * Request JSON
     */
    body: EventRequestComment;
    path: {
        /**
         * Alert ID
         */
        id: string;
    };
    query?: never;
    url: '/alerts/{id}/comments/add';
};

export type PostAlertsByIdCommentsAddErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAlertsByIdCommentsAddError = PostAlertsByIdCommentsAddErrors[keyof PostAlertsByIdCommentsAddErrors];

export type PostAlertsByIdCommentsAddResponses = {
    /**
     * OK
     */
    200: EventResponseSingleAlert;
};

export type PostAlertsByIdCommentsAddResponse = PostAlertsByIdCommentsAddResponses[keyof PostAlertsByIdCommentsAddResponses];

export type PostAlertsByIdCommentsDeleteData = {
    /**
     * Request JSON
     */
    body: EventRequestId;
    path: {
        /**
         * Alert ID
         */
        id: string;
    };
    query?: never;
    url: '/alerts/{id}/comments/delete';
};

export type PostAlertsByIdCommentsDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAlertsByIdCommentsDeleteError = PostAlertsByIdCommentsDeleteErrors[keyof PostAlertsByIdCommentsDeleteErrors];

export type PostAlertsByIdCommentsDeleteResponses = {
    /**
     * OK
     */
    200: EventResponseSingleAlert;
};

export type PostAlertsByIdCommentsDeleteResponse = PostAlertsByIdCommentsDeleteResponses[keyof PostAlertsByIdCommentsDeleteResponses];

export type PostAlertsByIdLabelsAddData = {
    /**
     * Request JSON
     */
    body: EventRequestKeyValue;
    path: {
        /**
         * Alert ID
         */
        id: string;
    };
    query?: never;
    url: '/alerts/{id}/labels/add';
};

export type PostAlertsByIdLabelsAddErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAlertsByIdLabelsAddError = PostAlertsByIdLabelsAddErrors[keyof PostAlertsByIdLabelsAddErrors];

export type PostAlertsByIdLabelsAddResponses = {
    /**
     * OK
     */
    200: EventResponseSingleAlert;
};

export type PostAlertsByIdLabelsAddResponse = PostAlertsByIdLabelsAddResponses[keyof PostAlertsByIdLabelsAddResponses];

export type PostAlertsByIdLabelsDeleteData = {
    /**
     * Request JSON
     */
    body: EventRequestKey;
    path: {
        /**
         * Alert ID
         */
        id: string;
    };
    query?: never;
    url: '/alerts/{id}/labels/delete';
};

export type PostAlertsByIdLabelsDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAlertsByIdLabelsDeleteError = PostAlertsByIdLabelsDeleteErrors[keyof PostAlertsByIdLabelsDeleteErrors];

export type PostAlertsByIdLabelsDeleteResponses = {
    /**
     * OK
     */
    200: EventResponseSingleAlert;
};

export type PostAlertsByIdLabelsDeleteResponse = PostAlertsByIdLabelsDeleteResponses[keyof PostAlertsByIdLabelsDeleteResponses];

export type PostAlertsByIdStatusSetData = {
    /**
     * Request JSON
     */
    body: EventRequestStatus;
    path: {
        /**
         * Alert ID
         */
        id: string;
    };
    query?: never;
    url: '/alerts/{id}/status/set';
};

export type PostAlertsByIdStatusSetErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAlertsByIdStatusSetError = PostAlertsByIdStatusSetErrors[keyof PostAlertsByIdStatusSetErrors];

export type PostAlertsByIdStatusSetResponses = {
    /**
     * OK
     */
    200: EventResponseSingleAlert;
};

export type PostAlertsByIdStatusSetResponse = PostAlertsByIdStatusSetResponses[keyof PostAlertsByIdStatusSetResponses];

export type PostAlertsCreateData = {
    /**
     * Webhook JSON
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query: {
        /**
         * Webhook source
         */
        source: string;
    };
    url: '/alerts/create';
};

export type PostAlertsCreateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAlertsCreateError = PostAlertsCreateErrors[keyof PostAlertsCreateErrors];

export type PostAlertsCreateResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetAlertsStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/alerts/stats';
};

export type GetAlertsStatsErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetAlertsStatsError = GetAlertsStatsErrors[keyof GetAlertsStatsErrors];

export type GetAlertsStatsResponses = {
    /**
     * OK
     */
    200: EventResponseAlertsStats;
};

export type GetAlertsStatsResponse = GetAlertsStatsResponses[keyof GetAlertsStatsResponses];

export type GetAuthLoginByProviderData = {
    body?: never;
    path: {
        /**
         * OAuth provider: yandex, vk, keycloak
         */
        provider: string;
    };
    query?: never;
    url: '/auth/login/{provider}';
};

export type GetAuthLoginByProviderCallbackData = {
    body?: never;
    path: {
        /**
         * OAuth provider: yandex, vk, keycloak
         */
        provider: string;
    };
    query?: never;
    url: '/auth/login/{provider}/callback';
};

export type PostAuthLoginEmailData = {
    /**
     * Request JSON
     */
    body: UserRequestEmailCode;
    path?: never;
    query?: never;
    url: '/auth/login/email';
};

export type PostAuthLoginEmailErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAuthLoginEmailError = PostAuthLoginEmailErrors[keyof PostAuthLoginEmailErrors];

export type PostAuthLoginEmailResponses = {
    /**
     * OK
     */
    200: UserResponseAccessJwt;
};

export type PostAuthLoginEmailResponse = PostAuthLoginEmailResponses[keyof PostAuthLoginEmailResponses];

export type PostAuthLoginEmailCodeData = {
    /**
     * Request JSON
     */
    body: UserRequestEmail;
    path?: never;
    query?: never;
    url: '/auth/login/email/code';
};

export type PostAuthLoginEmailCodeErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAuthLoginEmailCodeError = PostAuthLoginEmailCodeErrors[keyof PostAuthLoginEmailCodeErrors];

export type PostAuthLoginEmailCodeResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostAuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * OK
     */
    200: UserResponseAccessJwt;
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type GetEscalationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/escalations';
};

export type GetEscalationsErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetEscalationsError = GetEscalationsErrors[keyof GetEscalationsErrors];

export type GetEscalationsResponses = {
    /**
     * OK
     */
    200: TenantResponseEscalationList;
};

export type GetEscalationsResponse = GetEscalationsResponses[keyof GetEscalationsResponses];

export type GetEscalationsByIdData = {
    body?: never;
    path: {
        /**
         * Escalation ID
         */
        id: string;
    };
    query?: never;
    url: '/escalations/{id}';
};

export type GetEscalationsByIdErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetEscalationsByIdError = GetEscalationsByIdErrors[keyof GetEscalationsByIdErrors];

export type GetEscalationsByIdResponses = {
    /**
     * OK
     */
    200: TenantResponseSingleEscalation;
};

export type GetEscalationsByIdResponse = GetEscalationsByIdResponses[keyof GetEscalationsByIdResponses];

export type PostEscalationsByIdConditionCreateData = {
    /**
     * Request JSON
     */
    body: TenantRequestCondition;
    path: {
        /**
         * Escalation ID
         */
        id: string;
    };
    query?: never;
    url: '/escalations/{id}/condition/create';
};

export type PostEscalationsByIdConditionCreateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostEscalationsByIdConditionCreateError = PostEscalationsByIdConditionCreateErrors[keyof PostEscalationsByIdConditionCreateErrors];

export type PostEscalationsByIdConditionCreateResponses = {
    /**
     * OK
     */
    200: TenantResponseSingleCondition;
};

export type PostEscalationsByIdConditionCreateResponse = PostEscalationsByIdConditionCreateResponses[keyof PostEscalationsByIdConditionCreateResponses];

export type PostEscalationsByIdConditionDeleteData = {
    /**
     * Request JSON
     */
    body: TenantRequestNumber;
    path: {
        /**
         * Escalation ID
         */
        id: string;
    };
    query?: never;
    url: '/escalations/{id}/condition/delete';
};

export type PostEscalationsByIdConditionDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostEscalationsByIdConditionDeleteError = PostEscalationsByIdConditionDeleteErrors[keyof PostEscalationsByIdConditionDeleteErrors];

export type PostEscalationsByIdConditionDeleteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostEscalationsByIdStepCreateData = {
    /**
     * Request JSON
     */
    body: TenantRequestStep;
    path: {
        /**
         * Escalation ID
         */
        id: string;
    };
    query?: never;
    url: '/escalations/{id}/step/create';
};

export type PostEscalationsByIdStepCreateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostEscalationsByIdStepCreateError = PostEscalationsByIdStepCreateErrors[keyof PostEscalationsByIdStepCreateErrors];

export type PostEscalationsByIdStepCreateResponses = {
    /**
     * OK
     */
    200: TenantResponseSingleStep;
};

export type PostEscalationsByIdStepCreateResponse = PostEscalationsByIdStepCreateResponses[keyof PostEscalationsByIdStepCreateResponses];

export type PostEscalationsByIdStepDeleteData = {
    /**
     * Request JSON
     */
    body: TenantRequestNumber;
    path: {
        /**
         * Escalation ID
         */
        id: string;
    };
    query?: never;
    url: '/escalations/{id}/step/delete';
};

export type PostEscalationsByIdStepDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostEscalationsByIdStepDeleteError = PostEscalationsByIdStepDeleteErrors[keyof PostEscalationsByIdStepDeleteErrors];

export type PostEscalationsByIdStepDeleteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostEscalationsByIdUpdateData = {
    /**
     * Request JSON
     */
    body: TenantRequestEscalation;
    path: {
        /**
         * Escalation ID
         */
        id: string;
    };
    query?: never;
    url: '/escalations/{id}/update';
};

export type PostEscalationsByIdUpdateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostEscalationsByIdUpdateError = PostEscalationsByIdUpdateErrors[keyof PostEscalationsByIdUpdateErrors];

export type PostEscalationsByIdUpdateResponses = {
    /**
     * OK
     */
    200: TenantResponseSingleEscalation;
};

export type PostEscalationsByIdUpdateResponse = PostEscalationsByIdUpdateResponses[keyof PostEscalationsByIdUpdateResponses];

export type GetIncidentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Incident status
         */
        status?: number;
        /**
         * Incidents limit
         */
        limit?: number;
        /**
         * Incidents offset
         */
        offset?: number;
    };
    url: '/incidents';
};

export type GetIncidentsErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetIncidentsError = GetIncidentsErrors[keyof GetIncidentsErrors];

export type GetIncidentsResponses = {
    /**
     * OK
     */
    200: EventResponseIncidentList;
};

export type GetIncidentsResponse = GetIncidentsResponses[keyof GetIncidentsResponses];

export type GetIncidentsByIdData = {
    body?: never;
    path: {
        /**
         * Incident ID
         */
        id: string;
    };
    query?: never;
    url: '/incidents/{id}';
};

export type GetIncidentsByIdErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetIncidentsByIdError = GetIncidentsByIdErrors[keyof GetIncidentsByIdErrors];

export type GetIncidentsByIdResponses = {
    /**
     * OK
     */
    200: EventResponseSingleIncident;
};

export type GetIncidentsByIdResponse = GetIncidentsByIdResponses[keyof GetIncidentsByIdResponses];

export type PostIncidentsByIdAlertsAddData = {
    /**
     * Request JSON
     */
    body: EventRequestId;
    path: {
        /**
         * Incident ID
         */
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/alerts/add';
};

export type PostIncidentsByIdAlertsAddErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostIncidentsByIdAlertsAddError = PostIncidentsByIdAlertsAddErrors[keyof PostIncidentsByIdAlertsAddErrors];

export type PostIncidentsByIdAlertsAddResponses = {
    /**
     * OK
     */
    200: EventResponseSingleIncident;
};

export type PostIncidentsByIdAlertsAddResponse = PostIncidentsByIdAlertsAddResponses[keyof PostIncidentsByIdAlertsAddResponses];

export type PostIncidentsByIdAlertsDeleteData = {
    /**
     * Request JSON
     */
    body: EventRequestId;
    path: {
        /**
         * Incident ID
         */
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/alerts/delete';
};

export type PostIncidentsByIdAlertsDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostIncidentsByIdAlertsDeleteError = PostIncidentsByIdAlertsDeleteErrors[keyof PostIncidentsByIdAlertsDeleteErrors];

export type PostIncidentsByIdAlertsDeleteResponses = {
    /**
     * OK
     */
    200: EventResponseSingleIncident;
};

export type PostIncidentsByIdAlertsDeleteResponse = PostIncidentsByIdAlertsDeleteResponses[keyof PostIncidentsByIdAlertsDeleteResponses];

export type PostIncidentsByIdCommentsAddData = {
    /**
     * Request JSON
     */
    body: EventRequestComment;
    path: {
        /**
         * Incident ID
         */
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/comments/add';
};

export type PostIncidentsByIdCommentsAddErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostIncidentsByIdCommentsAddError = PostIncidentsByIdCommentsAddErrors[keyof PostIncidentsByIdCommentsAddErrors];

export type PostIncidentsByIdCommentsAddResponses = {
    /**
     * OK
     */
    200: EventResponseSingleIncident;
};

export type PostIncidentsByIdCommentsAddResponse = PostIncidentsByIdCommentsAddResponses[keyof PostIncidentsByIdCommentsAddResponses];

export type PostIncidentsByIdCommentsDeleteData = {
    /**
     * Request JSON
     */
    body: EventRequestId;
    path: {
        /**
         * Incident ID
         */
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/comments/delete';
};

export type PostIncidentsByIdCommentsDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostIncidentsByIdCommentsDeleteError = PostIncidentsByIdCommentsDeleteErrors[keyof PostIncidentsByIdCommentsDeleteErrors];

export type PostIncidentsByIdCommentsDeleteResponses = {
    /**
     * OK
     */
    200: EventResponseSingleIncident;
};

export type PostIncidentsByIdCommentsDeleteResponse = PostIncidentsByIdCommentsDeleteResponses[keyof PostIncidentsByIdCommentsDeleteResponses];

export type PostIncidentsByIdLabelsAddData = {
    /**
     * Request JSON
     */
    body: EventRequestKeyValue;
    path: {
        /**
         * Incident ID
         */
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/labels/add';
};

export type PostIncidentsByIdLabelsAddErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostIncidentsByIdLabelsAddError = PostIncidentsByIdLabelsAddErrors[keyof PostIncidentsByIdLabelsAddErrors];

export type PostIncidentsByIdLabelsAddResponses = {
    /**
     * OK
     */
    200: EventResponseSingleIncident;
};

export type PostIncidentsByIdLabelsAddResponse = PostIncidentsByIdLabelsAddResponses[keyof PostIncidentsByIdLabelsAddResponses];

export type PostIncidentsByIdLabelsDeleteData = {
    /**
     * Request JSON
     */
    body: EventRequestKey;
    path: {
        /**
         * Incident ID
         */
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/labels/delete';
};

export type PostIncidentsByIdLabelsDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostIncidentsByIdLabelsDeleteError = PostIncidentsByIdLabelsDeleteErrors[keyof PostIncidentsByIdLabelsDeleteErrors];

export type PostIncidentsByIdLabelsDeleteResponses = {
    /**
     * OK
     */
    200: EventResponseSingleIncident;
};

export type PostIncidentsByIdLabelsDeleteResponse = PostIncidentsByIdLabelsDeleteResponses[keyof PostIncidentsByIdLabelsDeleteResponses];

export type PostIncidentsByIdStatusSetData = {
    /**
     * Request JSON
     */
    body: EventRequestStatus;
    path: {
        /**
         * Incident ID
         */
        id: string;
    };
    query?: never;
    url: '/incidents/{id}/status/set';
};

export type PostIncidentsByIdStatusSetErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostIncidentsByIdStatusSetError = PostIncidentsByIdStatusSetErrors[keyof PostIncidentsByIdStatusSetErrors];

export type PostIncidentsByIdStatusSetResponses = {
    /**
     * OK
     */
    200: EventResponseSingleIncident;
};

export type PostIncidentsByIdStatusSetResponse = PostIncidentsByIdStatusSetResponses[keyof PostIncidentsByIdStatusSetResponses];

export type PostIncidentsCreateData = {
    /**
     * Request JSON
     */
    body: EventRequestIncident;
    path?: never;
    query?: never;
    url: '/incidents/create';
};

export type PostIncidentsCreateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostIncidentsCreateError = PostIncidentsCreateErrors[keyof PostIncidentsCreateErrors];

export type PostIncidentsCreateResponses = {
    /**
     * OK
     */
    200: EventResponseIncident;
};

export type PostIncidentsCreateResponse = PostIncidentsCreateResponses[keyof PostIncidentsCreateResponses];

export type GetSchedulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/schedules';
};

export type GetSchedulesErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetSchedulesError = GetSchedulesErrors[keyof GetSchedulesErrors];

export type GetSchedulesResponses = {
    /**
     * OK
     */
    200: TenantResponseScheduleList;
};

export type GetSchedulesResponse = GetSchedulesResponses[keyof GetSchedulesResponses];

export type GetSchedulesByIdData = {
    body?: never;
    path: {
        /**
         * Schedule ID
         */
        id: string;
    };
    query: {
        /**
         * Since timestamp
         */
        since: number;
        /**
         * Until timestamp
         */
        until: number;
    };
    url: '/schedules/{id}';
};

export type GetSchedulesByIdErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetSchedulesByIdError = GetSchedulesByIdErrors[keyof GetSchedulesByIdErrors];

export type GetSchedulesByIdResponses = {
    /**
     * OK
     */
    200: TenantResponseSingleSchedule;
};

export type GetSchedulesByIdResponse = GetSchedulesByIdResponses[keyof GetSchedulesByIdResponses];

export type PostSchedulesByIdOverrideCreateData = {
    /**
     * Request JSON
     */
    body: TenantRequestOverride;
    path: {
        /**
         * Schedule ID
         */
        id: string;
    };
    query: {
        /**
         * Since timestamp
         */
        since: number;
        /**
         * Until timestamp
         */
        until: number;
    };
    url: '/schedules/{id}/override/create';
};

export type PostSchedulesByIdOverrideCreateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostSchedulesByIdOverrideCreateError = PostSchedulesByIdOverrideCreateErrors[keyof PostSchedulesByIdOverrideCreateErrors];

export type PostSchedulesByIdOverrideCreateResponses = {
    /**
     * OK
     */
    200: TenantResponseSingleOverride;
};

export type PostSchedulesByIdOverrideCreateResponse = PostSchedulesByIdOverrideCreateResponses[keyof PostSchedulesByIdOverrideCreateResponses];

export type PostSchedulesByIdOverrideDeleteData = {
    /**
     * Request JSON
     */
    body: TenantRequestNumber;
    path: {
        /**
         * Schedule ID
         */
        id: string;
    };
    query?: never;
    url: '/schedules/{id}/override/delete';
};

export type PostSchedulesByIdOverrideDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostSchedulesByIdOverrideDeleteError = PostSchedulesByIdOverrideDeleteErrors[keyof PostSchedulesByIdOverrideDeleteErrors];

export type PostSchedulesByIdOverrideDeleteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostSchedulesByIdRotationCreateData = {
    /**
     * Request JSON
     */
    body: TenantRequestRotation;
    path: {
        /**
         * Schedule ID
         */
        id: string;
    };
    query: {
        /**
         * Since timestamp
         */
        since: number;
        /**
         * Until timestamp
         */
        until: number;
    };
    url: '/schedules/{id}/rotation/create';
};

export type PostSchedulesByIdRotationCreateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostSchedulesByIdRotationCreateError = PostSchedulesByIdRotationCreateErrors[keyof PostSchedulesByIdRotationCreateErrors];

export type PostSchedulesByIdRotationCreateResponses = {
    /**
     * OK
     */
    200: TenantResponseSingleRotation;
};

export type PostSchedulesByIdRotationCreateResponse = PostSchedulesByIdRotationCreateResponses[keyof PostSchedulesByIdRotationCreateResponses];

export type PostSchedulesByIdRotationDeleteData = {
    /**
     * Request JSON
     */
    body: TenantRequestNumber;
    path: {
        /**
         * Schedule ID
         */
        id: string;
    };
    query?: never;
    url: '/schedules/{id}/rotation/delete';
};

export type PostSchedulesByIdRotationDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostSchedulesByIdRotationDeleteError = PostSchedulesByIdRotationDeleteErrors[keyof PostSchedulesByIdRotationDeleteErrors];

export type PostSchedulesByIdRotationDeleteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetSchedulesByIdShiftsData = {
    body?: never;
    path: {
        /**
         * Schedule ID
         */
        id: string;
    };
    query?: {
        /**
         * Target timestamp
         */
        timestamp?: number;
    };
    url: '/schedules/{id}/shifts';
};

export type GetSchedulesByIdShiftsErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetSchedulesByIdShiftsError = GetSchedulesByIdShiftsErrors[keyof GetSchedulesByIdShiftsErrors];

export type GetSchedulesByIdShiftsResponses = {
    /**
     * OK
     */
    200: TenantResponseShiftList;
};

export type GetSchedulesByIdShiftsResponse = GetSchedulesByIdShiftsResponses[keyof GetSchedulesByIdShiftsResponses];

export type PostSchedulesByIdUpdateData = {
    /**
     * Request JSON
     */
    body: TenantRequestSchedule;
    path: {
        /**
         * Schedule ID
         */
        id: string;
    };
    query?: never;
    url: '/schedules/{id}/update';
};

export type PostSchedulesByIdUpdateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostSchedulesByIdUpdateError = PostSchedulesByIdUpdateErrors[keyof PostSchedulesByIdUpdateErrors];

export type PostSchedulesByIdUpdateResponses = {
    /**
     * OK
     */
    200: TenantResponseSingleSchedule;
};

export type PostSchedulesByIdUpdateResponse = PostSchedulesByIdUpdateResponses[keyof PostSchedulesByIdUpdateResponses];

export type GetSettingsAuthProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/auth-providers';
};

export type GetSettingsAuthProvidersErrors = {
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetSettingsAuthProvidersError = GetSettingsAuthProvidersErrors[keyof GetSettingsAuthProvidersErrors];

export type GetSettingsAuthProvidersResponses = {
    /**
     * OK
     */
    200: SettingsResponseAuthProviderList;
};

export type GetSettingsAuthProvidersResponse = GetSettingsAuthProvidersResponses[keyof GetSettingsAuthProvidersResponses];

export type GetSettingsFeaturesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/features';
};

export type GetSettingsFeaturesErrors = {
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetSettingsFeaturesError = GetSettingsFeaturesErrors[keyof GetSettingsFeaturesErrors];

export type GetSettingsFeaturesResponses = {
    /**
     * OK
     */
    200: SettingsResponseFeatureList;
};

export type GetSettingsFeaturesResponse = GetSettingsFeaturesResponses[keyof GetSettingsFeaturesResponses];

export type GetTenantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants';
};

export type GetTenantsErrors = {
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetTenantsError = GetTenantsErrors[keyof GetTenantsErrors];

export type GetTenantsResponses = {
    /**
     * OK
     */
    200: TenantResponseTenantList;
};

export type GetTenantsResponse = GetTenantsResponses[keyof GetTenantsResponses];

export type GetTenantsByIdEscalationsData = {
    body?: never;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/escalations';
};

export type GetTenantsByIdEscalationsErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetTenantsByIdEscalationsError = GetTenantsByIdEscalationsErrors[keyof GetTenantsByIdEscalationsErrors];

export type GetTenantsByIdEscalationsResponses = {
    /**
     * OK
     */
    200: TenantResponseEscalationList;
};

export type GetTenantsByIdEscalationsResponse = GetTenantsByIdEscalationsResponses[keyof GetTenantsByIdEscalationsResponses];

export type PostTenantsByIdEscalationsCreateData = {
    /**
     * Request JSON
     */
    body: TenantRequestEscalation;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/escalations/create';
};

export type PostTenantsByIdEscalationsCreateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsByIdEscalationsCreateError = PostTenantsByIdEscalationsCreateErrors[keyof PostTenantsByIdEscalationsCreateErrors];

export type PostTenantsByIdEscalationsCreateResponses = {
    /**
     * OK
     */
    200: TenantResponseSingleEscalation;
};

export type PostTenantsByIdEscalationsCreateResponse = PostTenantsByIdEscalationsCreateResponses[keyof PostTenantsByIdEscalationsCreateResponses];

export type PostTenantsByIdEscalationsDeleteData = {
    /**
     * Request JSON
     */
    body: TenantRequestId;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/escalations/delete';
};

export type PostTenantsByIdEscalationsDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsByIdEscalationsDeleteError = PostTenantsByIdEscalationsDeleteErrors[keyof PostTenantsByIdEscalationsDeleteErrors];

export type PostTenantsByIdEscalationsDeleteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetTenantsByIdMembersData = {
    body?: never;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/members';
};

export type GetTenantsByIdMembersErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetTenantsByIdMembersError = GetTenantsByIdMembersErrors[keyof GetTenantsByIdMembersErrors];

export type GetTenantsByIdMembersResponses = {
    /**
     * OK
     */
    200: TenantResponseMemberList;
};

export type GetTenantsByIdMembersResponse = GetTenantsByIdMembersResponses[keyof GetTenantsByIdMembersResponses];

export type PostTenantsByIdMembersDeleteData = {
    /**
     * Request JSON
     */
    body: TenantRequestId;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/members/delete';
};

export type PostTenantsByIdMembersDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsByIdMembersDeleteError = PostTenantsByIdMembersDeleteErrors[keyof PostTenantsByIdMembersDeleteErrors];

export type PostTenantsByIdMembersDeleteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostTenantsByIdMembersUpdateData = {
    /**
     * Request JSON
     */
    body: TenantRequestMember;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/members/update';
};

export type PostTenantsByIdMembersUpdateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsByIdMembersUpdateError = PostTenantsByIdMembersUpdateErrors[keyof PostTenantsByIdMembersUpdateErrors];

export type PostTenantsByIdMembersUpdateResponses = {
    /**
     * OK
     */
    200: TenantResponseSingleMember;
};

export type PostTenantsByIdMembersUpdateResponse = PostTenantsByIdMembersUpdateResponses[keyof PostTenantsByIdMembersUpdateResponses];

export type GetTenantsByIdSchedulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants/{id}/schedules';
};

export type GetTenantsByIdSchedulesErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetTenantsByIdSchedulesError = GetTenantsByIdSchedulesErrors[keyof GetTenantsByIdSchedulesErrors];

export type GetTenantsByIdSchedulesResponses = {
    /**
     * OK
     */
    200: TenantResponseScheduleList;
};

export type GetTenantsByIdSchedulesResponse = GetTenantsByIdSchedulesResponses[keyof GetTenantsByIdSchedulesResponses];

export type PostTenantsByIdSchedulesCreateData = {
    /**
     * Request JSON
     */
    body: TenantRequestNewSchedule;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/schedules/create';
};

export type PostTenantsByIdSchedulesCreateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsByIdSchedulesCreateError = PostTenantsByIdSchedulesCreateErrors[keyof PostTenantsByIdSchedulesCreateErrors];

export type PostTenantsByIdSchedulesCreateResponses = {
    /**
     * OK
     */
    200: TenantResponseSingleSchedule;
};

export type PostTenantsByIdSchedulesCreateResponse = PostTenantsByIdSchedulesCreateResponses[keyof PostTenantsByIdSchedulesCreateResponses];

export type PostTenantsByIdSchedulesDeleteData = {
    /**
     * Request JSON
     */
    body: TenantRequestId;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/schedules/delete';
};

export type PostTenantsByIdSchedulesDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsByIdSchedulesDeleteError = PostTenantsByIdSchedulesDeleteErrors[keyof PostTenantsByIdSchedulesDeleteErrors];

export type PostTenantsByIdSchedulesDeleteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetTenantsByIdTokensData = {
    body?: never;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/tokens';
};

export type GetTenantsByIdTokensErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetTenantsByIdTokensError = GetTenantsByIdTokensErrors[keyof GetTenantsByIdTokensErrors];

export type GetTenantsByIdTokensResponses = {
    /**
     * OK
     */
    200: TenantResponseTokenList;
};

export type GetTenantsByIdTokensResponse = GetTenantsByIdTokensResponses[keyof GetTenantsByIdTokensResponses];

export type PostTenantsByIdTokensCreateData = {
    /**
     * Request JSON
     */
    body: TenantRequestName;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/tokens/create';
};

export type PostTenantsByIdTokensCreateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsByIdTokensCreateError = PostTenantsByIdTokensCreateErrors[keyof PostTenantsByIdTokensCreateErrors];

export type PostTenantsByIdTokensCreateResponses = {
    /**
     * OK
     */
    200: TenantResponseSingleToken;
};

export type PostTenantsByIdTokensCreateResponse = PostTenantsByIdTokensCreateResponses[keyof PostTenantsByIdTokensCreateResponses];

export type PostTenantsByIdTokensDeleteData = {
    /**
     * Request JSON
     */
    body: TenantRequestId;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/tokens/delete';
};

export type PostTenantsByIdTokensDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsByIdTokensDeleteError = PostTenantsByIdTokensDeleteErrors[keyof PostTenantsByIdTokensDeleteErrors];

export type PostTenantsByIdTokensDeleteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostTenantsByIdUpdateData = {
    /**
     * Request JSON
     */
    body: TenantRequestName;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/update';
};

export type PostTenantsByIdUpdateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsByIdUpdateError = PostTenantsByIdUpdateErrors[keyof PostTenantsByIdUpdateErrors];

export type PostTenantsByIdUpdateResponses = {
    /**
     * Created
     */
    201: TenantResponseSingleTenant;
};

export type PostTenantsByIdUpdateResponse = PostTenantsByIdUpdateResponses[keyof PostTenantsByIdUpdateResponses];

export type PostTenantsCreateData = {
    /**
     * Request JSON
     */
    body: TenantRequestName;
    path?: never;
    query?: never;
    url: '/tenants/create';
};

export type PostTenantsCreateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostTenantsCreateError = PostTenantsCreateErrors[keyof PostTenantsCreateErrors];

export type PostTenantsCreateResponses = {
    /**
     * Created
     */
    201: TenantResponseSingleTenant;
};

export type PostTenantsCreateResponse = PostTenantsCreateResponses[keyof PostTenantsCreateResponses];

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type GetUserErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * OK
     */
    200: UserResponseSingleUser;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetUserContactsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/contacts';
};

export type GetUserContactsErrors = {
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetUserContactsError = GetUserContactsErrors[keyof GetUserContactsErrors];

export type GetUserContactsResponses = {
    /**
     * OK
     */
    200: UserResponseContactsList;
};

export type GetUserContactsResponse = GetUserContactsResponses[keyof GetUserContactsResponses];

export type PostUserContactsByIdDeleteData = {
    body?: never;
    path: {
        /**
         * Contact ID
         */
        id: string;
    };
    query?: never;
    url: '/user/contacts/{id}/delete';
};

export type PostUserContactsByIdDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostUserContactsByIdDeleteError = PostUserContactsByIdDeleteErrors[keyof PostUserContactsByIdDeleteErrors];

export type PostUserContactsByIdDeleteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostUserContactsByIdVerifyData = {
    /**
     * Request JSON
     */
    body: UserRequestCode;
    path: {
        /**
         * Contact ID
         */
        id: string;
    };
    query?: never;
    url: '/user/contacts/{id}/verify';
};

export type PostUserContactsByIdVerifyErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostUserContactsByIdVerifyError = PostUserContactsByIdVerifyErrors[keyof PostUserContactsByIdVerifyErrors];

export type PostUserContactsByIdVerifyResponses = {
    /**
     * OK
     */
    200: UserResponseSingleContact;
};

export type PostUserContactsByIdVerifyResponse = PostUserContactsByIdVerifyResponses[keyof PostUserContactsByIdVerifyResponses];

export type PostUserContactsAddData = {
    /**
     * Request JSON
     */
    body: UserRequestContact;
    path?: never;
    query?: never;
    url: '/user/contacts/add';
};

export type PostUserContactsAddErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostUserContactsAddError = PostUserContactsAddErrors[keyof PostUserContactsAddErrors];

export type PostUserContactsAddResponses = {
    /**
     * Created
     */
    201: UserResponseSingleContact;
};

export type PostUserContactsAddResponse = PostUserContactsAddResponses[keyof PostUserContactsAddResponses];

export type GetUserSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/sessions';
};

export type GetUserSessionsErrors = {
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type GetUserSessionsError = GetUserSessionsErrors[keyof GetUserSessionsErrors];

export type GetUserSessionsResponses = {
    /**
     * OK
     */
    200: UserResponseSessions;
};

export type GetUserSessionsResponse = GetUserSessionsResponses[keyof GetUserSessionsResponses];

export type PostUserSessionsCloseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/sessions/close';
};

export type PostUserSessionsCloseErrors = {
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostUserSessionsCloseError = PostUserSessionsCloseErrors[keyof PostUserSessionsCloseErrors];

export type PostUserSessionsCloseResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostUserUpdateData = {
    /**
     * Request JSON
     */
    body: UserRequestParameter;
    path?: never;
    query?: never;
    url: '/user/update';
};

export type PostUserUpdateErrors = {
    /**
     * Bad Request
     */
    400: ServerResponseError;
    /**
     * Unauthorized
     */
    401: ServerResponseError;
    /**
     * Internal Server Error
     */
    500: ServerResponseError;
};

export type PostUserUpdateError = PostUserUpdateErrors[keyof PostUserUpdateErrors];

export type PostUserUpdateResponses = {
    /**
     * OK
     */
    200: UserResponseSingleUser;
};

export type PostUserUpdateResponse = PostUserUpdateResponses[keyof PostUserUpdateResponses];
