// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'localhost:8080/api/v1' | (string & {});
};

export type ServerErrorResponse = {
    error?: string;
    request_id?: string;
};

export type TenantCreateHandlerRequestBody = {
    name: string;
};

export type TenantCreateTokenHandlerRequestBody = {
    name: string;
};

export type TenantDeleteMembersHandlerRequestBody = {
    id: string;
};

export type TenantDeleteTokenHandlerRequestBody = {
    id: string;
};

export type TenantUpdateMembersHandlerRequestBody = {
    id: string;
    role: 'admin' | 'editor' | 'viewer';
};

export type UserAddContactHandlerRequestBody = {
    kind: 'email' | 'telegram' | 'phone';
    value: string;
};

export type UserEmailLoginHandlerRequestBody = {
    code: string;
    email: string;
};

export type UserRequestEmailCodeHandlerRequestBody = {
    email: string;
};

export type UserVerifyContactHandlerRequestBody = {
    code: string;
};

export type GetAuthLoginByProviderData = {
    body?: never;
    path: {
        /**
         * OAuth provider: yandex, vk, keycloak
         */
        provider: string;
    };
    query?: never;
    url: '/auth/login/{provider}';
};

export type GetAuthLoginByProviderCallbackData = {
    body?: never;
    path: {
        /**
         * OAuth provider: yandex, vk, keycloak
         */
        provider: string;
    };
    query?: never;
    url: '/auth/login/{provider}/callback';
};

export type PostAuthLoginEmailData = {
    /**
     * Request JSON
     */
    body: UserEmailLoginHandlerRequestBody;
    path?: never;
    query?: never;
    url: '/auth/login/email';
};

export type PostAuthLoginEmailErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type PostAuthLoginEmailError = PostAuthLoginEmailErrors[keyof PostAuthLoginEmailErrors];

export type PostAuthLoginEmailResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostAuthLoginEmailResponse = PostAuthLoginEmailResponses[keyof PostAuthLoginEmailResponses];

export type PostAuthLoginEmailCodeData = {
    /**
     * Request JSON
     */
    body: UserRequestEmailCodeHandlerRequestBody;
    path?: never;
    query?: never;
    url: '/auth/login/email/code';
};

export type PostAuthLoginEmailCodeErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type PostAuthLoginEmailCodeError = PostAuthLoginEmailCodeErrors[keyof PostAuthLoginEmailCodeErrors];

export type PostAuthLoginEmailCodeResponses = {
    /**
     * Created
     */
    201: {
        [key: string]: string;
    };
};

export type PostAuthLoginEmailCodeResponse = PostAuthLoginEmailCodeResponses[keyof PostAuthLoginEmailCodeResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostAuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type GetTenantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants';
};

export type GetTenantsErrors = {
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type GetTenantsError = GetTenantsErrors[keyof GetTenantsErrors];

export type GetTenantsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetTenantsResponse = GetTenantsResponses[keyof GetTenantsResponses];

export type GetTenantsByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants/{id}';
};

export type GetTenantsByIdErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type GetTenantsByIdError = GetTenantsByIdErrors[keyof GetTenantsByIdErrors];

export type GetTenantsByIdResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetTenantsByIdResponse = GetTenantsByIdResponses[keyof GetTenantsByIdResponses];

export type PostTenantsByIdDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants/{id}/delete';
};

export type PostTenantsByIdDeleteErrors = {
    /**
     * Not Implemented
     */
    501: unknown;
};

export type GetTenantsByIdMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants/{id}/members';
};

export type GetTenantsByIdMembersErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type GetTenantsByIdMembersError = GetTenantsByIdMembersErrors[keyof GetTenantsByIdMembersErrors];

export type GetTenantsByIdMembersResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetTenantsByIdMembersResponse = GetTenantsByIdMembersResponses[keyof GetTenantsByIdMembersResponses];

export type PostTenantsByIdMembersDeleteData = {
    /**
     * Request JSON
     */
    body: TenantDeleteMembersHandlerRequestBody;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/members/delete';
};

export type PostTenantsByIdMembersDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type PostTenantsByIdMembersDeleteError = PostTenantsByIdMembersDeleteErrors[keyof PostTenantsByIdMembersDeleteErrors];

export type PostTenantsByIdMembersDeleteResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostTenantsByIdMembersDeleteResponse = PostTenantsByIdMembersDeleteResponses[keyof PostTenantsByIdMembersDeleteResponses];

export type PostTenantsByIdMembersUpdateData = {
    /**
     * Request JSON
     */
    body: TenantUpdateMembersHandlerRequestBody;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/members/update';
};

export type PostTenantsByIdMembersUpdateErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type PostTenantsByIdMembersUpdateError = PostTenantsByIdMembersUpdateErrors[keyof PostTenantsByIdMembersUpdateErrors];

export type PostTenantsByIdMembersUpdateResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostTenantsByIdMembersUpdateResponse = PostTenantsByIdMembersUpdateResponses[keyof PostTenantsByIdMembersUpdateResponses];

export type GetTenantsByIdTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants/{id}/tokens';
};

export type GetTenantsByIdTokensErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type GetTenantsByIdTokensError = GetTenantsByIdTokensErrors[keyof GetTenantsByIdTokensErrors];

export type GetTenantsByIdTokensResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetTenantsByIdTokensResponse = GetTenantsByIdTokensResponses[keyof GetTenantsByIdTokensResponses];

export type PostTenantsByIdTokensCreateData = {
    /**
     * Request JSON
     */
    body: TenantCreateTokenHandlerRequestBody;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/tokens/create';
};

export type PostTenantsByIdTokensCreateErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type PostTenantsByIdTokensCreateError = PostTenantsByIdTokensCreateErrors[keyof PostTenantsByIdTokensCreateErrors];

export type PostTenantsByIdTokensCreateResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostTenantsByIdTokensCreateResponse = PostTenantsByIdTokensCreateResponses[keyof PostTenantsByIdTokensCreateResponses];

export type PostTenantsByIdTokensDeleteData = {
    /**
     * Request JSON
     */
    body: TenantDeleteTokenHandlerRequestBody;
    path: {
        /**
         * Tenant ID
         */
        id: string;
    };
    query?: never;
    url: '/tenants/{id}/tokens/delete';
};

export type PostTenantsByIdTokensDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
};

export type PostTenantsByIdTokensDeleteError = PostTenantsByIdTokensDeleteErrors[keyof PostTenantsByIdTokensDeleteErrors];

export type PostTenantsByIdTokensDeleteResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostTenantsByIdTokensDeleteResponse = PostTenantsByIdTokensDeleteResponses[keyof PostTenantsByIdTokensDeleteResponses];

export type PostTenantsByIdUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants/{id}/update';
};

export type PostTenantsByIdUpdateErrors = {
    /**
     * Not Implemented
     */
    501: unknown;
};

export type PostTenantsCreateData = {
    /**
     * Request JSON
     */
    body: TenantCreateHandlerRequestBody;
    path?: never;
    query?: never;
    url: '/tenants/create';
};

export type PostTenantsCreateErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type PostTenantsCreateError = PostTenantsCreateErrors[keyof PostTenantsCreateErrors];

export type PostTenantsCreateResponses = {
    /**
     * Created
     */
    201: {
        [key: string]: string;
    };
};

export type PostTenantsCreateResponse = PostTenantsCreateResponses[keyof PostTenantsCreateResponses];

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type GetUserErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetUserContactsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/contacts';
};

export type GetUserContactsErrors = {
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type GetUserContactsError = GetUserContactsErrors[keyof GetUserContactsErrors];

export type GetUserContactsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetUserContactsResponse = GetUserContactsResponses[keyof GetUserContactsResponses];

export type PostUserContactsByIdDeleteData = {
    body?: never;
    path: {
        /**
         * Contact ID
         */
        id: string;
    };
    query?: never;
    url: '/user/contacts/{id}/delete';
};

export type PostUserContactsByIdDeleteErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type PostUserContactsByIdDeleteError = PostUserContactsByIdDeleteErrors[keyof PostUserContactsByIdDeleteErrors];

export type PostUserContactsByIdDeleteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostUserContactsByIdVerifyData = {
    /**
     * Request JSON
     */
    body: UserVerifyContactHandlerRequestBody;
    path: {
        /**
         * Contact ID
         */
        id: string;
    };
    query?: never;
    url: '/user/contacts/{id}/verify';
};

export type PostUserContactsByIdVerifyErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type PostUserContactsByIdVerifyError = PostUserContactsByIdVerifyErrors[keyof PostUserContactsByIdVerifyErrors];

export type PostUserContactsByIdVerifyResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostUserContactsByIdVerifyResponse = PostUserContactsByIdVerifyResponses[keyof PostUserContactsByIdVerifyResponses];

export type PostUserContactsAddData = {
    /**
     * Request JSON
     */
    body: UserAddContactHandlerRequestBody;
    path?: never;
    query?: never;
    url: '/user/contacts/add';
};

export type PostUserContactsAddErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type PostUserContactsAddError = PostUserContactsAddErrors[keyof PostUserContactsAddErrors];

export type PostUserContactsAddResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostUserContactsAddResponse = PostUserContactsAddResponses[keyof PostUserContactsAddResponses];

export type PostUserUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/update';
};

export type PostUserUpdateErrors = {
    /**
     * Bad Request
     */
    400: ServerErrorResponse;
    /**
     * Unauthorized
     */
    401: ServerErrorResponse;
    /**
     * Internal Server Error
     */
    500: ServerErrorResponse;
};

export type PostUserUpdateError = PostUserUpdateErrors[keyof PostUserUpdateErrors];

export type PostUserUpdateResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostUserUpdateResponse = PostUserUpdateResponses[keyof PostUserUpdateResponses];
